---
- name: install base packages
  apt: pkg={{ item }} state=latest
  with_items:
    - ntp
    - vim
    - git
    - tar
    - curl
    - apache2
    - php5
    - python-software-properties

- name: install apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter
  notify: restart apache

- name: install php5 packages
  become: yes
  become_user: root
  apt: pkg={{ item }} state=present
  with_items:
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-intl
    - php5-ldap
    - php5-mcrypt
    - php5-tidy
    - php5-mysql
    - php5-xmlrpc
    - php5-xsl
    - php5-intl
    - php5-apcu
  notify: restart apache

- name: create web folders
  file: state=directory path=/sites/mysite/{{ item }} owner=www-data group=www-data mode=2775
  with_items:
    - logs
    - shared/assets

- name: set default vhost
  template: src=etc/apache2/sites-available/default.j2 dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache

- name: add composer group
  group: name=composer state=present

- name: add composer user
  user: name=composer state=present group=composer generate_ssh_key=yes

- name: set no strict host checking for the composer user on github repos
  copy: dest=/home/composer/.ssh/config content="Host github.com\n\tStrictHostKeyChecking no\n"

- name: php.display_errors = on
  ini_file: dest=/etc/php5/{{ item }}/php.ini section=PHP option=display_errors value="On" backup=yes state=present
  with_items:
    - apache2
    - cli
  notify: restart apache

- name: php.display_startup_errors = on
  ini_file: dest=/etc/php5/{{ item }}/php.ini section=PHP option=display_startup_errors value="On" backup=yes state=present
  with_items:
    - apache2
    - cli
  notify: restart apache

- name: download sspak
  get_url: url=http://silverstripe.github.io/sspak/sspak.phar dest=/usr/bin/sspak mode=0777
